#! /usr/bin/env bash

dbus_session_file=~/.dbus/session-bus/$(cat /var/lib/dbus/machine-id)-0
if [ -e "$dbus_session_file" ]; then
    . "$dbus_session_file"
    export DBUS_SESSION_BUS_ADDRESS DBUS_SESSION_BUS_PID
fi

export eval $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)
PATH=$PATH:~/.scripts

mbsync gmail
